# Generated by Django 2.2.5 on 2020-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('academicDegree', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
